[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_unflags =
  -std=gnu++11

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++17

lib_deps =
  lemmingDev/ESP32-BLE-Gamepad
  h2zero/NimBLE-Arduino@^2.1.0

monitor_filters =
  esp32_exception_decoder

board_build.flash_mode = qio
board_build.f_cpu = 240000000L
